# Generated by Django 5.0.7 on 2024-08-23 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=40)),
                ('school', models.CharField(max_length=100)),
                ('teamTier', models.IntegerField(default=0)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_leader', to=settings.AUTH_USER_MODEL)),
                ('member2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_member2', to=settings.AUTH_USER_MODEL)),
                ('member3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_member3', to=settings.AUTH_USER_MODEL)),
                ('member4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_member4', to=settings.AUTH_USER_MODEL)),
                ('member5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_member5', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
    ]
