# Generated by Django 5.0.7 on 2024-08-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="teamTier",
        ),
        migrations.AlterField(
            model_name="team",
            name="leader",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="team",
            name="member2",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="team",
            name="member3",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="team",
            name="member4",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="team",
            name="member5",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="team",
            name="school",
            field=models.CharField(max_length=500),
        ),
    ]
