# Generated by Django 5.0.7 on 2024-08-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="school",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
