# Generated by Django 5.0.7 on 2024-08-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_nickname_user_age_user_game_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='puuid',
            field=models.CharField(blank=True, default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='tag_line',
            field=models.CharField(blank=True, default='00', max_length=100),
        ),
    ]
