# Generated by Django 5.0.7 on 2024-08-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("match", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="openChatUrl",
            field=models.URLField(blank=True),
        ),
    ]
