# Generated by Django 5.0.7 on 2024-08-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("match", "0002_match_openchaturl"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="user",
        ),
        migrations.AlterField(
            model_name="match",
            name="teamName",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
